-- TASK-020: identify the operational expense generated by a waste movement.
-- The direct relation makes the automatic row traceable and lets L-09 lock it.

ALTER TABLE "operational_expenses"
ADD COLUMN "stock_transaction_id" INTEGER;

CREATE UNIQUE INDEX "operational_expenses_stock_transaction_id_key"
ON "operational_expenses"("stock_transaction_id");

ALTER TABLE "operational_expenses"
ADD CONSTRAINT "operational_expenses_stock_transaction_id_fkey"
FOREIGN KEY ("stock_transaction_id") REFERENCES "stock_transactions"("id")
ON DELETE RESTRICT ON UPDATE CASCADE;

-- A zero-value waste remains auditable when stock exists with average_cost = 0.
-- Manual expenses still have to be strictly positive.
ALTER TABLE "operational_expenses"
DROP CONSTRAINT "expenses_amount_positive";

ALTER TABLE "operational_expenses"
ADD CONSTRAINT "expenses_amount_positive"
CHECK (
  "amount" > 0 OR
  ("amount" = 0 AND "stock_transaction_id" IS NOT NULL)
);
